apiVersion: v1
kind: Namespace
metadata:
  name: com-gft-deuba-unity-release-1
  labels: 
    demo/project: com.gft.deuba.unity.release-1
    demo/app: step-1
    config.istio.io/admission-webhooks: disabled
    istio-injection: disabled
