---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: com-gft-deuba-unity-release-1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    PROJECT: com.gft.deuba.unity.release-1
    app.kubernetes.io/part-of: step-1
    app.kubernetes.io/component: frontend
