---

apiVersion: v1
kind: Pod
metadata:
  name: thermometer-2
  namespace: com-gft-deuba-unity-release-1
  labels:
    demo/project: com.gft.deuba.unity.release-1
    demo/app: step-1
    demo/module: thermometer
    demo/version: "2.0.0"
spec:
  containers:
    - name: thermometer
      image: com.gft.deuba.unity.release-1.application.ms-measure:v2
      imagePullPolicy: Never
      args: [ "--type", "thermometer", "--address", "01:00", "--name", "thermometer-2", "--randomsvc", "http://random/random" ]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

