##############################################################################
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: frontend
    version: "1.0.0"
spec:
  selector:
    PROJECT: com.gft.deuba.unity.release-1
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      appProtocol: http
      name: http-frontend
