##############################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thermometer-ingress-api
  namespace: com-gft-deuba-unity-release-1
  labels:
    PROJECT: com.gft.deuba.unity.release-1
    app: thermometer

spec:

  hosts:

    - "mysite-pilot.localgft.com"

  gateways:

    - app-ingress-gateway

  http:

# ----------------------------------------------------------------------------

    - name: thermometer-pre-prod

      match:

      - uri:
          prefix: /thermometer/

        headers:
          origin:
            regex: .*mysite-uat.localgft.com.*

      - uri:
          prefix: /thermometer/

        headers:
          x-environment: 
            exact: pre-prod

      - uri:

          prefix: /thermometer/

        headers:
          Cookie:
            regex: (.*;\s*)?environment=pre-prod(\s*;.*)?

      rewrite:
        uri: /

      headers:
        request:
          set:
            x-environment: pre-prod

        response:
          set:
            x-environment: pre-prod

      route:
        - destination:
            host: thermometer
            subset: pre-prod

#       corsPolicy:
#         allowOrigins:
#         - regex: ".*"
#         allowMethods:
#         - GET
#         - POST
#         - OPTIONS
#         maxAge: 24h
#         allowCredentials: true

# ----------------------------------------------------------------------------

    - name: thermometer-prod

      match:

      - uri:
          prefix: /thermometer/

        headers:
          origin:
            regex: .*mysite-prod.localgft.com.*

      - uri:
          prefix: /thermometer/

        headers:
          x-environment: 
            exact: prod

      - uri:

          prefix: /thermometer/

        headers:
          Cookie:
            regex: (.*;\s*)?environment=prod(\s*;.*)?

      rewrite:
        uri: /

      headers:
        request:
          set:
            x-environment: prod

        response:
          set:
            x-environment: prod

      route:
        - destination:
            host: thermometer
            subset: prod

#       corsPolicy:
#         allowOrigins:
#         - exact: "mysite-prod.localgft.com"
#         - exact: "mysite-uat.localgft.com"
#         allowHeaders:
#           - "*"
#         allowMethods:
#         - GET
#         - POST
#         - OPTIONS
#         maxAge: 24h
#         allowCredentials: true


