name: Build go (local)

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
      - "src/go/**"
      
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
      with:  project

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      shell: bash
      working-directory:  "${{ GITHUB_WORKSPACE }}/project/src/go"
      run: make all
