name: Build go (local)

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
      - "src/go/**"
      
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
      with: 
        path: "./project"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up build environment
      shell: bash
      run: |
        sudo apt-get install -y make
        ln -s /bin/bash /usr/bin/bash

    - name: Build
      shell: bash
      working-directory:  "./project/src/go/ms-measure"
      run: |
        source setup.sh
        make bin
