---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: step-2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    demo/project: com.gft.deuba.unity.release-1
    demo/app: step-2
    demo/module: frontend
